%% *Matching Events*
% This page contains a list of all matching events.
%
FormatSpec1 = '%-20s %-20s %-8s %-9s %-7s %-7s %-7s %-7s %-7s %-7s\n';
FormatSpec2 = '%-20s %-20s %-8s %-9s %-7s %-7s \n';
%% _Summary_
disp('----- Matching Events -----')
if size(matching.cat1,1) >= 1000
    disp(' ')
    disp('Matching Event List too long to display')
else
    disp(' ')
    disp([num2str(size(matching.cat1,1)),' ',cat1.name,' and ',cat2.name, ' meet matching criteria.'])
    disp(' ')
    fprintf(FormatSpec1,'Event ID', 'Origin Time','Lat.','Lon.','Dep(km)','Mag','LocRes','DepRes','magRes','TimeRes')
    for ii = 1 : size(matching.cat1,1)
        fprintf(FormatSpec1,matching.cat1.ID{ii},...
            datestr(matching.cat1.OriginTime,'yyyy/mm/dd HH:MM:SS'),...
            num2str(matching.cat1.Latitude(ii)),...
            num2str(matching.cat1.Longitude(ii)),...
            num2str(matching.cat1.Depth(ii)),...
            num2str(matching.cat1.Mag(ii)),...
            num2str(matching.cat1.delD(ii)),...
            num2str(matching.cat1.delDepth(ii)),...
            num2str(matching.cat1.delMag(ii)),...
            num2str(matching.cat1.delTime(ii)*86400));
        fprintf(FormatSpec2,matching.cat2.ID{ii},...
            datestr(matching.cat2.OriginTime(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(matching.cat2.Latitude(ii)),...
            num2str(matching.cat2.Longitude(ii)),...
            num2str(matching.cat2.Depth(ii)),...
            num2str(matching.cat2.Mag(ii)));
        disp('----')
    end
end
