%% *Problem Events*
% This page contains lists of all problem events.  The order of the lists
% is: events with depth residuals greater than the threshold, events with
% magnitude residuals greather than the threshold, and events with depth
% AND magnitude residuals greater than the thresholds.
FormatSpec1 = '%-10s %-20s %-8s %-9s %-7s %-3s %-7s \n';
FormatSpec2 = '%-10s %-20s %-8s %-9s %-7s %-3s \n';
%% _Summary of Depth Differences_
if ~isempty(dep.cat1)
    delDepth = dep.cat1.Depth - dep.cat2.Depth;
    disp(['There are ',num2str(size(dep.cat1,1)),' events with different depths'])
    fprintf(FormatSpec1,'EventID', 'Origin Time', 'Lat.','Lon.','Dep(km)', 'Mag', 'Res(km)')
    for ii = 1 : size(dep.cat1,1)
        fprintf(FormatSpec1,dep.cat1.ID{ii},...
            datestr(dep.cat1.OriginTime(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(dep.cat1.Latitude(ii)),...
            num2str(dep.cat1.Longitude(ii)),...
            num2str(dep.cat1.Depth(ii)),...
            num2str(dep.cat1.Mag(ii)),...
            num2str(delDepth(ii)))
        fprintf(FormatSpec2,dep.cat2.ID{ii},...
            datestr(dep.cat2.OriginTime(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(dep.cat2.Latitude(ii)),...
            num2str(dep.cat2.Longitude(ii)),...
            num2str(dep.cat2.Depth(ii)),...
            num2str(dep.cat2.Mag(ii)));
        disp('--')
    end
else
    disp('No events')
end
    disp(' ')
%% _Summary of Magnitude Differences_
if ~isempty(mags.cat1)
    delMag = mags.cat1.Mag - mags.cat2.Mag;
    disp(['There are ',num2str(size(mags.cat1,1)),' events with different magnitudes'])
    fprintf(FormatSpec1,'Catalog 1', 'Origin Time', 'Lat.','Lon.','Dep(km)', 'Mag', 'Res')
    for ii = 1 : size(mags.cat1,1)
        fprintf(FormatSpec1,mags.cat1.ID{ii},...
            datestr(mags.cat1.OriginTime(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(mags.cat1.Latitude(ii)),...
            num2str(mags.cat1.Longitude(ii)),...
            num2str(mags.cat1.Depth(ii)),...
            num2str(mags.cat1.Mag(ii)),...
            num2str(delMag(ii)));
        fprintf(FormatSpec2,mags.cat2.ID{ii},...
            datestr(mags.cat2.OriginTime(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(mags.cat2.Latitude(ii)),....
            num2str(mags.cat2.Latitude(ii)),...
            num2str(mags.cat2.Depth(ii)),...
            num2str(mags.cat2.Mag(ii)));
        disp('--')
    end
else
    disp('No events')
end
disp(' ')
%% _Summary of Depth AND Magnitude Differences_
FormatSpec1 = '%-10s %-20s %-8s %-9s %-7s %-3s %-7s %-7s\n';
FormatSpec2 = '%-10s %-20s %-8s %-9s %-7s %-3s \n';
if ~isempty(both.cat1)
    delDepth = both.cat1.Depth - both.cat2.Depth;
    delMag = both.cat1.Mag - both.cat2.Mag;
    disp(['There are ',num2str(size(both.cat1,1)),' events with different depths'])
    fprintf(FormatSpec1,'Catalog 1', 'Origin Time', 'Lat.','Lon.','Dep(km)', 'Mag', 'DepRes','MagRes')
    for ii = 1 : size(both.events1,1)
        fprintf(FormatSpec1,both.cat1.ID{ii},...
            datestr(both.cat1(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(both.cat1.Latitude(ii)),...
            num2str(both.cat1.Longitude(ii)),...
            num2str(both.cat1.Depth(ii)),...
            num2str(both.cat1.Mag(ii)),...
            num2str(delDepth(ii)),...
            num2str(delMag(ii)))
        fprintf(FormatSpec2,both.cat2.ID{ii},...
            datestr(both.cat2.OriginTime(ii),'yyyy/mm/dd HH:MM:SS'),...
            num2str(both.cat2.Latitude(ii)),...
            num2str(both.cat2.Longitude(ii)),...
            num2str(both.cat2.Depth(ii)),...
            num2str(both.cat2.Mag(ii)));
        disp('--')
    end
else
    disp('No events')
end